### ISSUE TITLE
Implement design feedback

### ISSUE THREAD

**Issue by IllyaMoskvin** [art-institute-of-chicago/browser-extension#28]
See comment on #24. Additionally:

- Reduce font size in tombstone
- Give tombstone more breathing room from edges
- Use outline version of logo
- Move logo to top-left
- Don't use `artist_display`, use `artist_titles` with creation date(s)

**Comment by surreal8** [comment]
![chromePluginFeedback](https://user-images.githubusercontent.com/925523/62639271-d1a88200-b904-11e9-8ab0-f5210383c472.png)
After our review today, we have the following changes to implement (we can break out as individual issues later):
- More space above titles/below images, this is especially needed for longer titles
- Object title/artist should fit inside of container outlined in image
- Make title accept two lines and then ... link to object page
- Change background color to light grey used on AIC website
- Add GA event/tracking to image links

**Comment by IllyaMoskvin** [comment]
Spinning out GA event/tracking into #39.

Closed #24 to prevent overlooking old feedback. Copied here:

- Limit width to about 6-8 words
- Limit line count to 2
- Add ellipsis after that limit

Most of this is already captured above.

**Comment by surreal8** [comment]
Going to check with our designer on the latest fullscreen changes.

**Comment by nikhiltri** [comment]
Reverted back to the original design due to complications with focal point and crop.
