### ISSUE TITLE
Implement responsive images for performance

### ISSUE THREAD

**Issue by IllyaMoskvin** [art-institute-of-chicago/browser-extension#38]
This should allow us to balance load on IIIF server vs. delivering images close to the user's window size. See [Responsive images on MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) for more info. 

Recommended sizes to maximize likelihood of hitting an existing cache: 200, 400, 843.

Less likely, but also possible: 600, 1280, 1686.

**Comment by surreal8** [comment]
@IllyaMoskvin will try a different approach for fullscreen images using openseadragon

**Comment by IllyaMoskvin** [comment]
Implemented in c0967f8 using OpenSeadragon's ["legacy image pyramid"](https://openseadragon.github.io/examples/tilesource-legacy/) Tile Source.
